name: Run JS Tests
 
on:

  push:

    branches: [ "main" ]
 
jobs:

  test:

    runs-on: ubuntu-latest
 
    steps:

      - name: Checkout Code

        uses: actions/checkout@v4
 
      - name: Setup Node

        uses: actions/setup-node@v4

        with:

          node-version: '18'
 
      - name: Install Dependencies

        run: npm ci   # 🔥 better than npm install
 
      - name: Fix Permissions (IMPORTANT)

        run: chmod +x ./node_modules/.bin/jest
 
      - name: Run Tests

        run: npm test
 